version: '3.9'
services:

  db:
    container_name: 'db'
    image: postgres:15.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: on-failure
    environment:
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    ports:
      - '5432:5432'

  redis:
    container_name: 'redis'
    image: redis:5-alpine
    restart: on-failure
    volumes:
      - redis-data:/data
    ports:
      - '6379:6379'

  adminer:
    image: adminer:latest
    container_name: 'adminer'
    environment:
      ADMINER_DEFAULT_DB_NAME: '${POSTGRES_DB}'
    restart: on-failure
    ports:
      - '80:8080'

volumes:
  postgres_data:
  redis-data: