"""Added big inteeger to the author speciality model

Revision ID: f16d7bd66009
Revises: 0b4ba99f0f22
Create Date: 2023-09-06 15:27:19.046006

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f16d7bd66009"
down_revision: Union[str, None] = "0b4ba99f0f22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
